  <form action="<?php echo BASE_URL?>/user/register"  method="post">
    
    <label for="name">Usuario:</label><input type="text" name="name" id="name"/><br/>
    <label for="full_name">Nombre Completo:</label><input type="text" name="full_name" id="full_name"/><br/>
    <label for="email">Email:</label><input type="text" name="email" id="email"><br/>
    <label for="password">Contraseña:</label><input type="password" name="password" id="password"/><br/>
    <input type="submit" value="Registrar"/>
  </form>