<?php
/**
 * Front Controller
 * @package Garson
 */

/** @todo Check if session_start(); must be done everytime **/
session_start();

include "../lib/Autoloader.php";
Autoloader::registerAutoload();

/**
 * Paths for the application
 * Copied directly from zf-tool's generated Front Controller.
 */
defined('APPLICATION_PATH')
    || define('APPLICATION_PATH', realpath(dirname(__FILE__) .
    '/../application'));

$Config = Config::getInstance();

/**
 * Used all along the application, because of problems generated by Pretty URLs
 */
define('BASE_URL', $Config->base_url);

/**
 * Sets default time-zone
 */
date_default_timezone_set($Config->default_timezone);

/** Ensure lib/ is on include_path **/
set_include_path(
  implode(
    PATH_SEPARATOR,
    array(
      realpath( APPLICATION_PATH . '/../lib' ),
      get_include_path(),
    )
  )
);

$Request = Request::getInstance();
$controller = $Request->getController();
$action = $Request->getAction();

/**
 * @todo Make some validations, if the Controller or Action doesn't exists
 * the front controller should redirect to a Not Found page
 */

$Controller = new $controller();
$Controller->$action();