<?php
/**
 * Front Controller
 * @package Garson
 */

/**
 * Paths for the application
 * Copied directly from zf-tool's generated Front Controller.
 */
defined('APPLICATION_PATH')
    || define('APPLICATION_PATH', realpath(dirname(__FILE__) .
    '/../application'));

$Config = Config::getInstance();
/**
 * Used all along the application, because of problems generated by Pretty URLs
 */
define('BASE_URL', $Config->base_url);

/** Ensure library/ is on include_path **/
set_include_path(
  implode(
    PATH_SEPARATOR,
    array(
      realpath( APPLICATION_PATH . '/../library' ),
      get_include_path(),
    )
  )
);

$Request = Request::getInstance();
$controller = $Request->getController();
$action = $Request->getAction();

/**
 * @todo Make some validations, if the Controller or Action doesn't exists
 * the front controller should redirect to Not Found page
 */

$Controller = new $controller();
$Controller->$action();

/**
 * Include files based on the Instance's ClassName being created
 *
 * Gets Controller from application/controllers/
 * Gets Views from application/views/
 * Gets Models from application/models/
 * Every other class it gets it from application/core/
 *
 * For classes that doesn't form part of the core, you must include the file
 * by hand.
 *
 * @todo Put this function in a separated file.
 */
function __autoload($class_name)
{
    $class_name = ucwords($class_name);
    
    /** Application Specific Classes are inside this directories **/
    $named_directories = array
    (
      'Controller' => 'controllers/',
      'View' => 'views/',
      'Model' => 'models/',
    );
    $is_core = true;
    foreach ( $named_directories AS $name => $directory ) {
      if ( stristr($class_name, $name) && $class_name!=$name ){
          $path = $directory . $class_name;
          $is_core = false;
          break;
      }
    }
    /** All other classes are inside the core **/
    if ($is_core) {
        $path = 'core/' . $class_name;
    }
   
    /** add the application path and the php extension **/
    require_once APPLICATION_PATH . '/' . $path . '.php';
}