  <p>Ejemplo de uso del overlay</p>
  
  <ul>
    <li>Ejemplo de como abrir un mensaje desde javascript: <a href="javascript:void(0);" onclick="writeOverlay('Hola Mundo');">Español</a></li>
    <li>Example of how to open a message from javascript: <a href="javascript:void(0);" onclick="writeOverlay('Hello World');">English</a></li>
  </ul>
  
  <p><a href="<?php echo BASE_URL ?>/examples">Ejemplos</a></p>