  <p><strong>Bienvenidos al TianguisCabal!</strong></p>
  <p>Algunos destinos mientras está el codigo de la pagina</p>
 
  <ul>
  <li><a href="<?php echo BASE_URL ?>/examples">Ejemplos de Codigo</a></li>
  <li><a href="<?php echo BASE_URL ?>/concept">Concepto de Arquitectura</a></li>
  <li><a href="<?php echo BASE_URL ?>/category">Ejemplo de <acronym title="Create, Update, Read and Delete">CRUD</acronym></a></li>
  </ul>