<?php
/**
 * Default Layout
 * @todo Clearly state which are the _private_ variables
 * @package TianguisCabal
 */

/*
 * By default the server will send the "correct" encoding but is cleaner if we
 * define it, by example in layouts that generate plain text or XML.
 */
header("Content-Type: text/html; charset=utf-8");

/* Default XML and Encoding settings */
echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $_language_ ?>" lang="<?php echo $_language_ ?>">
    <head>
      <title>Tianguis Cabal - <?php echo $_title_ ?></title>
      <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
      <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/css/main.css" />
      <script charset="utf-8" type="text/javascript" src="<?php echo BASE_URL ?>/js/main.js"></script>
    </head>
    <body>
      <div id="main">
        
            <div id="overlay_shadow" class="hidden"></div>
            <div id="overlay" class="hidden">
              
              <div id="message">
              <?php if( isset($_message_) ){
                echo $_message_;
                echo '<script type="text/javascript">showOverlay();</script>';
              }?>
              </div>
              <div class="close_link"><a href="javascript:void(0);" onclick="closeOverlay();">Cerrar</a></div>
            </div>
        
        <div id="header">
            <h1><a href="<?php echo BASE_URL?>">Tianguis Cabal</a><?php echo $_title_?></h1>
        </div>
        
        <div id="content">
            <?php echo $_template_content_ ?>
        </div>
            
        <div id="footer">
            TianguisCabal <?php echo date('Y'); ?>
        </div>
      </div>
      <?php if ( $logs = Logger::getWebLog() ) {
        echo "<div id=\"logs\">\n\n";
        foreach( $logs AS $log ) {
        $Log= (object)$log;
        ?>
          <div class="log <?php echo $Log->level ?>">
            <span class="level"><?php echo ucwords($Log->level) ?></span>
            <span class="time"><?php echo date('d/m/Y h:m:s', $Log->time) ?></span><br/>
            <?php echo $Log->name?><br/>
            <?php if( !empty($Log->details) ) {?>
            <pre><?php echo htmlspecialchars($Log->details) ?></pre>
          <?php }?>
          <span class="uri"><?php echo $Log->uri ?></span>
          </div>
        <?php
        }
        echo "</div>\n\n";
      }?>
    </body>
</html>